menu:
  Home: /
  Archives: /archives

social:
  GitHub: https://github.com/your-username
  Twitter: https://twitter.com/your-username

excerpt_length: 200

tag:
  color: "#FF0000"
  background: "#FFFF00"

code:
  font_size: 14
  line_number: true

#custom_css: /path/to/custom.css